[package]
name = "bevy_mod_picking"
version = "0.1.0"
authors = ["Aevyrie <aevyrie@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/aevyrie/bevy_mod_picking/"
keywords = ["gamedev", "graphics", "picking", "bevy", "3d"]
categories = ["game-engines", "rendering"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.2.1"
#bevy = { git = "https://github.com/bevyengine/bevy", branch = "master" }